name: New Component Implementation
description: Add a new component to Morfeo
title: "[Component] Component "
body:
  - type: input
    id: name
    attributes:
      label: New Component Name
  - type: checkboxes
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: These are the tasks to do so that we can validate that the component was implemented successfully
      options:
        - label: Implemented component in morfeo component library
        - label: Added scss partial file to pandora theme
        - label: Someone reviewed that the component looks good and works well
